steps:
  # Install dependencies
  - name: 'node:20'
    entrypoint: npm
    args: ['install']

  # Build the application
  - name: 'node:20'
    entrypoint: npm
    args: ['run', 'build']

  # Deploy to Firebase Hosting
  - name: 'gcr.io/cloud-builders/firebase'
    args: ['deploy', '--only', 'hosting']
    env:
      - 'FIREBASE_TOKEN=${_FIREBASE_TOKEN}'

timeout: '1800s'

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _FIREBASE_TOKEN: ''  # This will be set in Cloud Build triggers

tags:
  - 'firebase-hosting'
  - 'production' 